
import time

import os
def clear():
  os.system("clear")

titanClass = "Vanguard."
titanName = "Bravo Tango-Seven Two Seven Four."
firstName = "Jack"
lastName = "Cooper"
titanProtcolOne = "Link to Pilot."
titanProtcolTwo = "Uphold the Mission."
titanProtocolThree = "Protect The Pilot."
print("System rebooting...")
time.sleep(3)
clear()

print("Datacore system online.")
time.sleep(3)
print("Titan Designation:", titanName)
time.sleep(3)
print("Chassis class:", titanClass)
time.sleep(3)
print("   ")
print("   ")
print("   ")
print("Defense systems check:")
time.sleep(2)
print("    Bodyshield status:")
time.sleep(2)
print("                         = Online.")
time.sleep(2)
print("    Vortex Shield status:")
time.sleep(2)
print("                         = Online.")
time.sleep(2)
print("    Electric Smoke status:")
time.sleep(2)
print("                         = Online.")
time.sleep(2.5)
print("Defense Systems online.")
time.sleep(3)
print("   ")
print("   ")
print("   ")
print("Offense systems check:")
time.sleep(2)
print("    Multi-Target Missle System status:")
time.sleep(2)
print("                         = Online.")
time.sleep(2)
print("    Acolyte Pod One status:")
time.sleep(2)
print("                         = Online.")
time.sleep(2)
print("    Acolyte Pod Two status:")
time.sleep(2)
print("                         = Online.")
time.sleep(2)
print("    Burst Core status:")
time.sleep(2)
print("                       = Online.")
time.sleep(2)
print("Offiense Systems online.")
time.sleep(5)
print("    ")
time.sleep(2)
print("Pilot systems check:")
time.sleep(2)
print("Pilot location: Searching...")
time.sleep(3)
print("Pilot embarked.")
time.sleep(2)
clear()
print("Pilot Registered:", lastName + ", " + firstName)
time.sleep(2)
print("Starting control transfer....")
time.sleep(3)
print("  Protocol One:", titanProtcolOne)
time.sleep(3)
print("  Protocol Two:", titanProtcolTwo)
time.sleep(3)
print("  Protocol Three:", titanProtocolThree)
time.sleep(2)
print(" ")
time.sleep(2)
print("Protocol One Status:")
time.sleep(4)
print("                 = Success.")
time.sleep(2)
print("Transfering Controls to Pilot", lastName)
